### ISSUE TITLE
Table detection configuration

### ISSUE THREAD

**Issue by ngnquan** [sun-asterisk-research/table_reconstruction#35]
## 📚 Documentation
Could you provide the hyps file to train table detection model with yolov5s? I tried but the model is not better than your provided weight. Thank you!

**Comment by chienlm-2537** [comment]
We use the defaults hyperparameters file of yolov5s. You can find it [here](https://github.com/ultralytics/yolov5/blob/4103ce9ad0393cc27f6c80457894ad7be0cb1f0d/data/hyps/hyp.scratch.yaml).
We train it with `batch size = 128` and `epochs = 10`
