### ISSUE TITLE
Transformer convert

### ISSUE THREAD

**Issue by thienbui** [sun-asterisk-research/table_reconstruction#36]
Anh ơi cho em hỏi, để chuyển model transformer sang onnx thì như nào ạ. Em thấy code này chuyển đc Seq2seq thôi đúng ko ạ. em cam on

**Comment by ghost** [comment]
@thienbui chào bạn, hình như bạn nhầm đôi chút vì cái package của bọn mình phát triển không phục vụ cho việc chuyển đổi mô hình sang dạng ONNX tuy nhiên nếu gặp khó khăn trong việc chuyển đổi mô hình transformer thì bạn có thể xem xét đến việc chia nhỏ thành từng phần hoặc viết custom converter xem sao.

**Comment by thienbui** [comment]
Sorry em comment nhầm ở repo khác.
