### ISSUE TITLE
OCR in table_reconstruction

### ISSUE THREAD

**Issue by JennyFai** [sun-asterisk-research/table_reconstruction#38]
How do you process the OCR part of this problem? Please tell me.

**Comment by ghost** [comment]
@JennyFai 
Hello. For OCR, you can use open source pretrained models such as [PaddlePaddleOCR](https://github.com/PaddlePaddle/Paddle) for English and Chinese, or [VietOCR](https://github.com/pbcquoc/vietocr) for Vietnamese

**Comment by JennyFai** [comment]
@hieubhm-1071  
Oh, how should I process the output of the line segmentation step as input for the OCR step?

**Comment by ghost** [comment]
@JennyFai 
Maybe your are misunderstanding the purpose of this package. It's mainly used for extract table structure  from document images as described here https://viblo.asia/p/thu-vien-table-reconstruction-va-bai-toan-tai-cau-truc-bang-QpmleMGDlrd

If your main concern is OCR, which is recognizing text from images, you can find out more about text detection and recognition at:
https://viblo.asia/p/nhan-dang-tieng-viet-cung-voi-transformer-ocr-Qpmlejjm5rd
https://viblo.asia/p/bai-toan-phat-hien-chu-text-detection-va-mo-hinh-db-phan-1-3Q75wNm9lWb

**Comment by JennyFai** [comment]
@hieubhm-1071 
My project is Table Recognition. I think I can base on your package and add the OCR part. I think the OCR step processing after Line segmentation (with border tables).

**Comment by ghost** [comment]
@JennyFai 
we provide table cells detection (result of line segmentation step). You should check our example notebook [here](https://github.com/sun-asterisk-research/table_reconstruction/blob/master/example/example.ipynb)
From  cell coordinates, you can crop out the cells from the table then add the OCR part

**Comment by JennyFai** [comment]
@hieubhm-1071 
Thank you so much for your guidance.
